export type CoinReward = { thread: number; reply: number; upvote: number; accepted: number };

export type SeoMeta = {
  title: string;
  metaDescription: string;
  canonicalPath: string;
  index: boolean;
  sitemapPriority: number;
  hreflangGroup?: string;
};

export type CategoryNode = {
  id: string;
  branch: "global" | "finance";
  slug: string;
  name: string;
  description: string;
  parentSlug?: string;
  allowedContent: Array<"thread" | "article" | "ea" | "indicator">;
  coinReward: CoinReward;
  locales: string[];
  children?: CategoryNode[];
  seo: SeoMeta;
};

export function getCategoryTree(): CategoryNode[] { return [
{
id: "cat-01",
branch: "finance",
slug: "trading-strategies",
name: "Trading Strategies & Discussion",
description: "Scalping, day, swing, position, grid/marti, hedging & correlations.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trading Strategies & Discussion – YoForex Community",
metaDescription: "Resources and discussions for trading strategies & discussion.",
canonicalPath: "/category/trading-strategies",
index: true, sitemapPriority: 0.9,
hreflangGroup: "trading-strategies",
},
children: [
{
id: "cat-01-scalping-m1-m15",
branch: "finance",
slug: "scalping-m1-m15",
name: "Scalping Strategies (M1–M15)",
description: "Scalping Strategies (M1–M15) discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Scalping Strategies (M1–M15) – YoForex Forum",
metaDescription: "Discuss scalping strategies (m1–m15) with traders worldwide.",
canonicalPath: "/category/trading-strategies/scalping-m1-m15",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-xauusd-scalping",
branch: "finance",
slug: "xauusd-scalping",
name: "XAUUSD Scalping",
description: "XAUUSD Scalping discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "XAUUSD Scalping – YoForex Forum",
metaDescription: "Discuss xauusd scalping with traders worldwide.",
canonicalPath: "/category/trading-strategies/xauusd-scalping",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-eurusd-scalping",
branch: "finance",
slug: "eurusd-scalping",
name: "EURUSD Scalping",
description: "EURUSD Scalping discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "EURUSD Scalping – YoForex Forum",
metaDescription: "Discuss eurusd scalping with traders worldwide.",
canonicalPath: "/category/trading-strategies/eurusd-scalping",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-crypto-scalping",
branch: "finance",
slug: "crypto-scalping",
name: "Crypto Scalping",
description: "Crypto Scalping discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Crypto Scalping – YoForex Forum",
metaDescription: "Discuss crypto scalping with traders worldwide.",
canonicalPath: "/category/trading-strategies/crypto-scalping",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-news-scalping",
branch: "finance",
slug: "news-scalping",
name: "News Scalping",
description: "News Scalping discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "News Scalping – YoForex Forum",
metaDescription: "Discuss news scalping with traders worldwide.",
canonicalPath: "/category/trading-strategies/news-scalping",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-day-trading",
branch: "finance",
slug: "day-trading",
name: "Day Trading (M15–H4)",
description: "Day Trading (M15–H4) discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Day Trading (M15–H4) – YoForex Forum",
metaDescription: "Discuss day trading (m15–h4) with traders worldwide.",
canonicalPath: "/category/trading-strategies/day-trading",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-swing-trading",
branch: "finance",
slug: "swing-trading",
name: "Swing Trading (H4–D1)",
description: "Swing Trading (H4–D1) discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Swing Trading (H4–D1) – YoForex Forum",
metaDescription: "Discuss swing trading (h4–d1) with traders worldwide.",
canonicalPath: "/category/trading-strategies/swing-trading",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-position-trading",
branch: "finance",
slug: "position-trading",
name: "Position Trading (D1–W1)",
description: "Position Trading (D1–W1) discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Position Trading (D1–W1) – YoForex Forum",
metaDescription: "Discuss position trading (d1–w1) with traders worldwide.",
canonicalPath: "/category/trading-strategies/position-trading",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-grid-martingale",
branch: "finance",
slug: "grid-martingale",
name: "Grid & Martingale Systems",
description: "Grid & Martingale Systems discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Grid & Martingale Systems – YoForex Forum",
metaDescription: "Discuss grid & martingale systems with traders worldwide.",
canonicalPath: "/category/trading-strategies/grid-martingale",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-hedging",
branch: "finance",
slug: "hedging",
name: "Hedging Strategies",
description: "Hedging Strategies discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Hedging Strategies – YoForex Forum",
metaDescription: "Discuss hedging strategies with traders worldwide.",
canonicalPath: "/category/trading-strategies/hedging",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
{
id: "cat-01-multi-pair-correlation",
branch: "finance",
slug: "multi-pair-correlation",
name: "Multi-Pair Correlation",
description: "Multi-Pair Correlation discussions and resources.",
parentSlug: "trading-strategies",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Multi-Pair Correlation – YoForex Forum",
metaDescription: "Discuss multi-pair correlation with traders worldwide.",
canonicalPath: "/category/trading-strategies/multi-pair-correlation",
index: true, sitemapPriority: 0.8,
hreflangGroup: "trading-strategies",
},
},
],
},
{
id: "cat-02",
branch: "finance",
slug: "ea-library",
name: "Expert Advisors (EA) Library",
description: "Robots by strategy, platform and performance tier.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Expert Advisors (EA) Library – YoForex Community",
metaDescription: "Resources and discussions for expert advisors (ea) library.",
canonicalPath: "/category/ea-library",
index: true, sitemapPriority: 0.9,
hreflangGroup: "ea-library",
},
children: [
{
id: "cat-02-scalping-eas",
branch: "finance",
slug: "scalping-eas",
name: "Scalping EAs",
description: "Scalping EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Scalping EAs – YoForex Forum",
metaDescription: "Discuss scalping eas with traders worldwide.",
canonicalPath: "/category/ea-library/scalping-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-grid-trading-eas",
branch: "finance",
slug: "grid-trading-eas",
name: "Grid Trading EAs",
description: "Grid Trading EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Grid Trading EAs – YoForex Forum",
metaDescription: "Discuss grid trading eas with traders worldwide.",
canonicalPath: "/category/ea-library/grid-trading-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-trend-following-eas",
branch: "finance",
slug: "trend-following-eas",
name: "Trend Following EAs",
description: "Trend Following EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trend Following EAs – YoForex Forum",
metaDescription: "Discuss trend following eas with traders worldwide.",
canonicalPath: "/category/ea-library/trend-following-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-breakout-eas",
branch: "finance",
slug: "breakout-eas",
name: "Breakout EAs",
description: "Breakout EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Breakout EAs – YoForex Forum",
metaDescription: "Discuss breakout eas with traders worldwide.",
canonicalPath: "/category/ea-library/breakout-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-news-trading-eas",
branch: "finance",
slug: "news-trading-eas",
name: "News Trading EAs",
description: "News Trading EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "News Trading EAs – YoForex Forum",
metaDescription: "Discuss news trading eas with traders worldwide.",
canonicalPath: "/category/ea-library/news-trading-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-mt4-eas",
branch: "finance",
slug: "mt4-eas",
name: "MT4 EAs",
description: "MT4 EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "MT4 EAs – YoForex Forum",
metaDescription: "Discuss mt4 eas with traders worldwide.",
canonicalPath: "/category/ea-library/mt4-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-mt5-eas",
branch: "finance",
slug: "mt5-eas",
name: "MT5 EAs",
description: "MT5 EAs discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "MT5 EAs – YoForex Forum",
metaDescription: "Discuss mt5 eas with traders worldwide.",
canonicalPath: "/category/ea-library/mt5-eas",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-ctrader-robots",
branch: "finance",
slug: "ctrader-robots",
name: "cTrader Robots",
description: "cTrader Robots discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "cTrader Robots – YoForex Forum",
metaDescription: "Discuss ctrader robots with traders worldwide.",
canonicalPath: "/category/ea-library/ctrader-robots",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-free-eas-0",
branch: "finance",
slug: "free-eas-0",
name: "Free EAs (0 coins)",
description: "Free EAs (0 coins) discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Free EAs (0 coins) – YoForex Forum",
metaDescription: "Discuss free eas (0 coins) with traders worldwide.",
canonicalPath: "/category/ea-library/free-eas-0",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-budget-eas-50-100",
branch: "finance",
slug: "budget-eas-50-100",
name: "Budget EAs (50–100 coins)",
description: "Budget EAs (50–100 coins) discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Budget EAs (50–100 coins) – YoForex Forum",
metaDescription: "Discuss budget eas (50–100 coins) with traders worldwide.",
canonicalPath: "/category/ea-library/budget-eas-50-100",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
{
id: "cat-02-premium-eas-200-500",
branch: "finance",
slug: "premium-eas-200-500",
name: "Premium EAs (200–500 coins)",
description: "Premium EAs (200–500 coins) discussions and resources.",
parentSlug: "ea-library",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Premium EAs (200–500 coins) – YoForex Forum",
metaDescription: "Discuss premium eas (200–500 coins) with traders worldwide.",
canonicalPath: "/category/ea-library/premium-eas-200-500",
index: true, sitemapPriority: 0.8,
hreflangGroup: "ea-library",
},
},
],
},
{
id: "cat-03",
branch: "finance",
slug: "indicators-templates",
name: "Custom Indicators & Templates",
description: "Indicators & full chart templates.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Custom Indicators & Templates – YoForex Community",
metaDescription: "Resources and discussions for custom indicators & templates.",
canonicalPath: "/category/indicators-templates",
index: true, sitemapPriority: 0.9,
hreflangGroup: "indicators-templates",
},
children: [
{
id: "cat-03-trend-indicators",
branch: "finance",
slug: "trend-indicators",
name: "Trend Indicators",
description: "Trend Indicators discussions and resources.",
parentSlug: "indicators-templates",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trend Indicators – YoForex Forum",
metaDescription: "Discuss trend indicators with traders worldwide.",
canonicalPath: "/category/indicators-templates/trend-indicators",
index: true, sitemapPriority: 0.8,
hreflangGroup: "indicators-templates",
},
},
{
id: "cat-03-oscillators-momentum",
branch: "finance",
slug: "oscillators-momentum",
name: "Oscillators & Momentum",
description: "Oscillators & Momentum discussions and resources.",
parentSlug: "indicators-templates",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Oscillators & Momentum – YoForex Forum",
metaDescription: "Discuss oscillators & momentum with traders worldwide.",
canonicalPath: "/category/indicators-templates/oscillators-momentum",
index: true, sitemapPriority: 0.8,
hreflangGroup: "indicators-templates",
},
},
{
id: "cat-03-volume-indicators",
branch: "finance",
slug: "volume-indicators",
name: "Volume Indicators",
description: "Volume Indicators discussions and resources.",
parentSlug: "indicators-templates",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Volume Indicators – YoForex Forum",
metaDescription: "Discuss volume indicators with traders worldwide.",
canonicalPath: "/category/indicators-templates/volume-indicators",
index: true, sitemapPriority: 0.8,
hreflangGroup: "indicators-templates",
},
},
{
id: "cat-03-sr-tools",
branch: "finance",
slug: "sr-tools",
name: "Support/Resistance Tools",
description: "Support/Resistance Tools discussions and resources.",
parentSlug: "indicators-templates",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Support/Resistance Tools – YoForex Forum",
metaDescription: "Discuss support/resistance tools with traders worldwide.",
canonicalPath: "/category/indicators-templates/sr-tools",
index: true, sitemapPriority: 0.8,
hreflangGroup: "indicators-templates",
},
},
{
id: "cat-03-template-packs",
branch: "finance",
slug: "template-packs",
name: "Complete Template Packages",
description: "Complete Template Packages discussions and resources.",
parentSlug: "indicators-templates",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Complete Template Packages – YoForex Forum",
metaDescription: "Discuss complete template packages with traders worldwide.",
canonicalPath: "/category/indicators-templates/template-packs",
index: true, sitemapPriority: 0.8,
hreflangGroup: "indicators-templates",
},
},
],
},
{
id: "cat-04",
branch: "finance",
slug: "broker-reviews",
name: "Broker Reviews & Directory",
description: "Real user experiences: ECN, MM, spreads, leverage and warnings.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Broker Reviews & Directory – YoForex Community",
metaDescription: "Resources and discussions for broker reviews & directory.",
canonicalPath: "/category/broker-reviews",
index: true, sitemapPriority: 0.9,
hreflangGroup: "broker-reviews",
},
children: [
{
id: "cat-04-ecn-brokers",
branch: "finance",
slug: "ecn-brokers",
name: "ECN Brokers",
description: "ECN Brokers discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "ECN Brokers – YoForex Forum",
metaDescription: "Discuss ecn brokers with traders worldwide.",
canonicalPath: "/category/broker-reviews/ecn-brokers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
{
id: "cat-04-market-maker-brokers",
branch: "finance",
slug: "market-maker-brokers",
name: "Market Maker Brokers",
description: "Market Maker Brokers discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Market Maker Brokers – YoForex Forum",
metaDescription: "Discuss market maker brokers with traders worldwide.",
canonicalPath: "/category/broker-reviews/market-maker-brokers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
{
id: "cat-04-low-spread-brokers",
branch: "finance",
slug: "low-spread-brokers",
name: "Low Spread Brokers",
description: "Low Spread Brokers discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Low Spread Brokers – YoForex Forum",
metaDescription: "Discuss low spread brokers with traders worldwide.",
canonicalPath: "/category/broker-reviews/low-spread-brokers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
{
id: "cat-04-high-leverage-brokers",
branch: "finance",
slug: "high-leverage-brokers",
name: "High Leverage Brokers",
description: "High Leverage Brokers discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "High Leverage Brokers – YoForex Forum",
metaDescription: "Discuss high leverage brokers with traders worldwide.",
canonicalPath: "/category/broker-reviews/high-leverage-brokers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
{
id: "cat-04-regulated-brokers",
branch: "finance",
slug: "regulated-brokers",
name: "Regulated Brokers (FCA, ASIC)",
description: "Regulated Brokers (FCA, ASIC) discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Regulated Brokers (FCA, ASIC) – YoForex Forum",
metaDescription: "Discuss regulated brokers (fca, asic) with traders worldwide.",
canonicalPath: "/category/broker-reviews/regulated-brokers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
{
id: "cat-04-scam-watch",
branch: "finance",
slug: "scam-watch",
name: "Scam Watch & Warnings",
description: "Scam Watch & Warnings discussions and resources.",
parentSlug: "broker-reviews",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Scam Watch & Warnings – YoForex Forum",
metaDescription: "Discuss scam watch & warnings with traders worldwide.",
canonicalPath: "/category/broker-reviews/scam-watch",
index: true, sitemapPriority: 0.8,
hreflangGroup: "broker-reviews",
},
},
],
},
{
id: "cat-05",
branch: "finance",
slug: "coding-dev",
name: "Coding & Development",
description: "MQL4/5, Python, backtesting & freelance gigs.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Coding & Development – YoForex Community",
metaDescription: "Resources and discussions for coding & development.",
canonicalPath: "/category/coding-dev",
index: true, sitemapPriority: 0.9,
hreflangGroup: "coding-dev",
},
children: [
{
id: "cat-05-mql4",
branch: "finance",
slug: "mql4",
name: "MQL4 Programming",
description: "MQL4 Programming discussions and resources.",
parentSlug: "coding-dev",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "MQL4 Programming – YoForex Forum",
metaDescription: "Discuss mql4 programming with traders worldwide.",
canonicalPath: "/category/coding-dev/mql4",
index: true, sitemapPriority: 0.8,
hreflangGroup: "coding-dev",
},
},
{
id: "cat-05-mql5",
branch: "finance",
slug: "mql5",
name: "MQL5 Programming",
description: "MQL5 Programming discussions and resources.",
parentSlug: "coding-dev",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "MQL5 Programming – YoForex Forum",
metaDescription: "Discuss mql5 programming with traders worldwide.",
canonicalPath: "/category/coding-dev/mql5",
index: true, sitemapPriority: 0.8,
hreflangGroup: "coding-dev",
},
},
{
id: "cat-05-python-bots",
branch: "finance",
slug: "python-bots",
name: "Python Trading Bots",
description: "Python Trading Bots discussions and resources.",
parentSlug: "coding-dev",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Python Trading Bots – YoForex Forum",
metaDescription: "Discuss python trading bots with traders worldwide.",
canonicalPath: "/category/coding-dev/python-bots",
index: true, sitemapPriority: 0.8,
hreflangGroup: "coding-dev",
},
},
{
id: "cat-05-strategy-backtesting",
branch: "finance",
slug: "strategy-backtesting",
name: "Strategy Backtesting",
description: "Strategy Backtesting discussions and resources.",
parentSlug: "coding-dev",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Strategy Backtesting – YoForex Forum",
metaDescription: "Discuss strategy backtesting with traders worldwide.",
canonicalPath: "/category/coding-dev/strategy-backtesting",
index: true, sitemapPriority: 0.8,
hreflangGroup: "coding-dev",
},
},
{
id: "cat-05-freelance-requests",
branch: "finance",
slug: "freelance-requests",
name: "Freelance Requests",
description: "Freelance Requests discussions and resources.",
parentSlug: "coding-dev",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Freelance Requests – YoForex Forum",
metaDescription: "Discuss freelance requests with traders worldwide.",
canonicalPath: "/category/coding-dev/freelance-requests",
index: true, sitemapPriority: 0.8,
hreflangGroup: "coding-dev",
},
},
],
},
{
id: "cat-06",
branch: "finance",
slug: "education",
name: "Education & Resources",
description: "Beginner to pro: TA/FA, risk & psychology.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Education & Resources – YoForex Community",
metaDescription: "Resources and discussions for education & resources.",
canonicalPath: "/category/education",
index: true, sitemapPriority: 0.9,
hreflangGroup: "education",
},
children: [
{
id: "cat-06-beginners-corner",
branch: "finance",
slug: "beginners-corner",
name: "Beginner's Corner",
description: "Beginner's Corner discussions and resources.",
parentSlug: "education",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Beginner's Corner – YoForex Forum",
metaDescription: "Discuss beginner's corner with traders worldwide.",
canonicalPath: "/category/education/beginners-corner",
index: true, sitemapPriority: 0.8,
hreflangGroup: "education",
},
},
{
id: "cat-06-technical-analysis",
branch: "finance",
slug: "technical-analysis",
name: "Technical Analysis",
description: "Technical Analysis discussions and resources.",
parentSlug: "education",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Technical Analysis – YoForex Forum",
metaDescription: "Discuss technical analysis with traders worldwide.",
canonicalPath: "/category/education/technical-analysis",
index: true, sitemapPriority: 0.8,
hreflangGroup: "education",
},
},
{
id: "cat-06-fundamental-analysis",
branch: "finance",
slug: "fundamental-analysis",
name: "Fundamental Analysis",
description: "Fundamental Analysis discussions and resources.",
parentSlug: "education",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Fundamental Analysis – YoForex Forum",
metaDescription: "Discuss fundamental analysis with traders worldwide.",
canonicalPath: "/category/education/fundamental-analysis",
index: true, sitemapPriority: 0.8,
hreflangGroup: "education",
},
},
{
id: "cat-06-risk-management",
branch: "finance",
slug: "risk-management",
name: "Risk Management",
description: "Risk Management discussions and resources.",
parentSlug: "education",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Risk Management – YoForex Forum",
metaDescription: "Discuss risk management with traders worldwide.",
canonicalPath: "/category/education/risk-management",
index: true, sitemapPriority: 0.8,
hreflangGroup: "education",
},
},
{
id: "cat-06-trading-psychology",
branch: "finance",
slug: "trading-psychology",
name: "Trading Psychology",
description: "Trading Psychology discussions and resources.",
parentSlug: "education",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trading Psychology – YoForex Forum",
metaDescription: "Discuss trading psychology with traders worldwide.",
canonicalPath: "/category/education/trading-psychology",
index: true, sitemapPriority: 0.8,
hreflangGroup: "education",
},
},
],
},
{
id: "cat-07",
branch: "finance",
slug: "journals-performance",
name: "Trading Journals & Performance",
description: "Live journals, EA performance, backtests & forward tests.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trading Journals & Performance – YoForex Community",
metaDescription: "Resources and discussions for trading journals & performance.",
canonicalPath: "/category/journals-performance",
index: true, sitemapPriority: 0.9,
hreflangGroup: "journals-performance",
},
children: [
{
id: "cat-07-live-trading-journals",
branch: "finance",
slug: "live-trading-journals",
name: "Live Trading Journals",
description: "Live Trading Journals discussions and resources.",
parentSlug: "journals-performance",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Live Trading Journals – YoForex Forum",
metaDescription: "Discuss live trading journals with traders worldwide.",
canonicalPath: "/category/journals-performance/live-trading-journals",
index: true, sitemapPriority: 0.8,
hreflangGroup: "journals-performance",
},
},
{
id: "cat-07-ea-performance-reports",
branch: "finance",
slug: "ea-performance-reports",
name: "EA Performance Reports",
description: "EA Performance Reports discussions and resources.",
parentSlug: "journals-performance",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "EA Performance Reports – YoForex Forum",
metaDescription: "Discuss ea performance reports with traders worldwide.",
canonicalPath: "/category/journals-performance/ea-performance-reports",
index: true, sitemapPriority: 0.8,
hreflangGroup: "journals-performance",
},
},
{
id: "cat-07-backtest-results",
branch: "finance",
slug: "backtest-results",
name: "Backtest Results",
description: "Backtest Results discussions and resources.",
parentSlug: "journals-performance",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Backtest Results – YoForex Forum",
metaDescription: "Discuss backtest results with traders worldwide.",
canonicalPath: "/category/journals-performance/backtest-results",
index: true, sitemapPriority: 0.8,
hreflangGroup: "journals-performance",
},
},
{
id: "cat-07-forward-test-results",
branch: "finance",
slug: "forward-test-results",
name: "Forward Test Results",
description: "Forward Test Results discussions and resources.",
parentSlug: "journals-performance",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Forward Test Results – YoForex Forum",
metaDescription: "Discuss forward test results with traders worldwide.",
canonicalPath: "/category/journals-performance/forward-test-results",
index: true, sitemapPriority: 0.8,
hreflangGroup: "journals-performance",
},
},
],
},
{
id: "cat-08",
branch: "finance",
slug: "tools-services",
name: "Tools & Services",
description: "VPS, copiers, signals, calculators & utilities.",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Tools & Services – YoForex Community",
metaDescription: "Resources and discussions for tools & services.",
canonicalPath: "/category/tools-services",
index: true, sitemapPriority: 0.9,
hreflangGroup: "tools-services",
},
children: [
{
id: "cat-08-vps-services",
branch: "finance",
slug: "vps-services",
name: "VPS Services",
description: "VPS Services discussions and resources.",
parentSlug: "tools-services",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "VPS Services – YoForex Forum",
metaDescription: "Discuss vps services with traders worldwide.",
canonicalPath: "/category/tools-services/vps-services",
index: true, sitemapPriority: 0.8,
hreflangGroup: "tools-services",
},
},
{
id: "cat-08-trade-copiers",
branch: "finance",
slug: "trade-copiers",
name: "Trade Copiers",
description: "Trade Copiers discussions and resources.",
parentSlug: "tools-services",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Trade Copiers – YoForex Forum",
metaDescription: "Discuss trade copiers with traders worldwide.",
canonicalPath: "/category/tools-services/trade-copiers",
index: true, sitemapPriority: 0.8,
hreflangGroup: "tools-services",
},
},
{
id: "cat-08-signal-services",
branch: "finance",
slug: "signal-services",
name: "Signal Services",
description: "Signal Services discussions and resources.",
parentSlug: "tools-services",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Signal Services – YoForex Forum",
metaDescription: "Discuss signal services with traders worldwide.",
canonicalPath: "/category/tools-services/signal-services",
index: true, sitemapPriority: 0.8,
hreflangGroup: "tools-services",
},
},
{
id: "cat-08-calculators-utilities",
branch: "finance",
slug: "calculators-utilities",
name: "Calculators & Utilities",
description: "Calculators & Utilities discussions and resources.",
parentSlug: "tools-services",
allowedContent: ["thread","article","ea","indicator"],
coinReward: { thread: 10, reply: 2, upvote: 1, accepted: 15 },
locales: ["en","zh","hi","es"],
seo: {
title: "Calculators & Utilities – YoForex Forum",
metaDescription: "Discuss calculators & utilities with traders worldwide.",
canonicalPath: "/category/tools-services/calculators-utilities",
index: true, sitemapPriority: 0.8,
hreflangGroup: "tools-services",
},
},
],
},
]; }

// Helper functions for working with the category tree
export function getAllCategories(): CategoryNode[] {
  const categories: CategoryNode[] = [];
  const tree = getCategoryTree();
  
  for (const category of tree) {
    categories.push(category);
    if (category.children) {
      categories.push(...category.children);
    }
  }
  
  return categories;
}

export function getCategoryBySlug(slug: string): CategoryNode | undefined {
  return getAllCategories().find(cat => cat.slug === slug);
}

export function getMainCategories(): CategoryNode[] {
  return getCategoryTree();
}

export function getSubcategories(parentSlug: string): CategoryNode[] {
  const parent = getCategoryBySlug(parentSlug);
  return parent?.children || [];
}
