version: '3.9'

# Production Docker Compose Configuration
# This configuration is designed to run the application container only
# Database (RDS/Neon) and Redis (ElastiCache/Managed) are external services

services:
  # YoForex Application (Production Mode)
  app:
    image: yoforex:latest  # Built from main Dockerfile
    container_name: yoforex-app-prod
    environment:
      # Node Environment
      NODE_ENV: production
      
      # Server Ports
      PORT: 5000
      API_PORT: 3001
      
      # CRITICAL: These must be set via environment or .env.production
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      
      # URLs - Set these to your production domain
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      EXPRESS_URL: ${EXPRESS_URL:-http://127.0.0.1:3001}
      
      # Optional: External Redis (if using ElastiCache or managed Redis)
      REDIS_URL: ${REDIS_URL}
      
      # Authentication
      REPLIT_CLIENT_ID: ${REPLIT_CLIENT_ID}
      REPLIT_CLIENT_SECRET: ${REPLIT_CLIENT_SECRET}
      
      # Payment Processing
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      
      # Email Service
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
      
      # Feature Flags
      EMAIL_NOTIFICATIONS_ENABLED: ${EMAIL_NOTIFICATIONS_ENABLED:-true}
      CACHE_ENABLED: ${CACHE_ENABLED:-true}
      GEOLOCALE_ENABLED: ${GEOLOCALE_ENABLED:-false}
      
      # Rate Limiting
      RATE_LIMIT_GENERAL: ${RATE_LIMIT_GENERAL:-100}
      RATE_LIMIT_WRITE: ${RATE_LIMIT_WRITE:-30}
      RATE_LIMIT_AUTH: ${RATE_LIMIT_AUTH:-10}
      
      # File Uploads
      MAX_UPLOAD_SIZE: ${MAX_UPLOAD_SIZE:-20}
      ALLOWED_FILE_TYPES: ${ALLOWED_FILE_TYPES:-.jpg,.jpeg,.png,.gif,.pdf,.zip,.mq4,.mq5,.ex4,.ex5}
      
      # Monitoring
      SENTRY_DSN: ${SENTRY_DSN}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
      # Analytics
      GA_TRACKING_ID: ${GA_TRACKING_ID}
      
    ports:
      - "5000:5000"    # Next.js Frontend
      - "3001:3001"    # Express API
    
    volumes:
      # Persistent storage for uploads
      - /var/www/yoforex/uploads:/app/public/uploads:rw
      
      # Log files
      - /var/log/yoforex:/app/logs:rw
      
    networks:
      - yoforex-prod-network
      
    # Health check configuration
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
          
    # Restart policy
    restart: always
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        labels: "service=yoforex,env=production"
        
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false  # False because Next.js needs to write to .next/cache
    tmpfs:
      - /tmp
      - /app/.next/cache
      
  # Optional: NGINX Reverse Proxy (if not using external load balancer)
  nginx:
    image: nginx:alpine
    container_name: yoforex-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/yoforex.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /var/log/nginx:/var/log/nginx:rw
    networks:
      - yoforex-prod-network
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  yoforex-prod-network:
    driver: bridge
    name: yoforex-prod-network
    ipam:
      config:
        - subnet: 172.20.0.0/16